language: r

sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - ggplot2

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e "covr::coveralls()"
  - Rscript -e "covr::codecov()"